# Generated by Django 3.2 on 2023-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20230209_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_autor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
